[app]
  name = "devcloud"
  description = "devcloud"
  internal_address = "http://127.0.0.1:8020"
  internal_token = "vCYg52HNzFcMMHq7sVLoFxHU"
  debug = true

[log]
  # 日志的级别, 默认Debug
  level = "debug"

[log.file]
  # 是否开启文件记录
  enable = true

[http]
  # 开启GRPC服务
  enable = true
  # HTTP服务Host
  host = "127.0.0.1"
  # HTTP服务端口
  port = 8020

[datasource]
  provider = "mysql"
  host = "127.0.0.1"
  port = 3306
  database = "devcloud_go18"
  username = "root"
  password = "123456"
  debug = true
  auto_migrate = true

[kafka]
  brokers = ["127.0.0.1:9092"]
  scram_algorithm = "SHA512"
  username = ""
  password = ""
  debug = false
