[app]
name = "exapmle"
key  = "this is your app key"

[http]
host = "127.0.0.1"
port = 8020

[datasource]
host = "127.0.0.1"
port = 3306
username = "root"
password = "123456"
database = "test"
debug = true
auto_migrate = true

[log]
level = "debug"

[log.file]
enable = true
file_path = "logs/app.log"